enabled: true
additional_trustees:
  - ericharper
  - ko3n1g
  - chtruong814
  - thomasdhc
  - pablo-garay
  - adil-a
  - akoumpa
  - ananthsub
  - athitten
  - bernardwin
  - hemildesai
  - maanug-nv
additional_vetters:
  - ericharper
  - ko3n1g
  - chtruong814
  - thomasdhc
  - pablo-garay
  - adil-a
  - akoumpa
  - ananthsub
  - athitten
  - bernardwin
  - hemildesai
  - maanug-nv
auto_sync_draft: false
auto_sync_ready: true
