comment: false
coverage:
  status:
    project: false
    patch:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_ci_failed: error
        if_not_found: success
  ignore:
    - "src/megatron/bridge/training/tokenizers/bert_tokenization.py"
    - "src/megatron/bridge/training/tokenizers/gpt2_tokenization.py"

fixes:
  - "/workspace/::"
