# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate static documentation from authoritative model verification cards."""

from __future__ import annotations

import argparse
import datetime
import json
import logging
import re
import shlex
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml


LOGGER = logging.getLogger(__name__)
CATALOG_SCHEMA_VERSION = 1
CARD_GLOB = "examples/model_verification_cards/*/card.yaml"
GENERATED_NOTICE = "<!-- Generated by scripts/docs/generate_model_verification_catalog.py. Do not edit. -->"
NAV_START = "# BEGIN GENERATED MODEL VERIFICATION CATALOG"
NAV_END = "# END GENERATED MODEL VERIFICATION CATALOG"
VALID_STATUSES = {"verified", "unverified", "unsupported", "not_applicable"}
STATUS_LABELS = {
    "verified": "✅ verified",
    "unverified": "⚪ unverified",
    "unsupported": "❌ unsupported",
    "not_applicable": "➖ not applicable",
}
TOPOLOGY_FLAGS = {
    "nodes": ("--nodes",),
    "gpus_per_node": ("--gpus-per-node", "--gpus_per_node"),
    "tensor_parallel": (
        "--tp",
        "--tensor-model-parallel-size",
        "--tensor_model_parallel_size",
        "model.tensor_model_parallel_size",
    ),
    "pipeline_parallel": (
        "--pp",
        "--pipeline-model-parallel-size",
        "--pipeline_model_parallel_size",
        "model.pipeline_model_parallel_size",
    ),
    "context_parallel": (
        "--cp",
        "--context-parallel-size",
        "--context_parallel_size",
        "model.context_parallel_size",
    ),
    "expert_parallel": (
        "--ep",
        "--expert-model-parallel-size",
        "--expert_model_parallel_size",
        "model.expert_model_parallel_size",
    ),
    "expert_tensor_parallel": (
        "--etp",
        "--expert-tensor-parallel-size",
        "--expert_tensor_parallel_size",
        "model.expert_tensor_parallel_size",
    ),
    "sequence_length": ("--seq-length", "--seq_length", "model.seq_length"),
    "recipe": ("--recipe",),
}


class CatalogError(ValueError):
    """Raised when a card cannot be normalized without inventing information."""


def _mapping(value: object, context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise CatalogError(f"{context} must be a mapping")
    return value


def _text(value: object | None) -> str | None:
    if value is None:
        return None
    if isinstance(value, (datetime.date, datetime.datetime)):
        return value.isoformat()
    return str(value)


def _json_value(value: object) -> object:
    if isinstance(value, dict):
        return {str(key): _json_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_value(item) for item in value]
    if isinstance(value, (datetime.date, datetime.datetime)):
        return value.isoformat()
    return value


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "entry"


def _commands(item: dict[str, Any], context: str) -> list[str]:
    command = item.get("command")
    commands = item.get("commands")
    if command is not None and commands is not None:
        raise CatalogError(f"{context} has both command and commands")
    if command is not None:
        return [str(command).strip()]
    if commands is None:
        return []
    if not isinstance(commands, list) or not all(isinstance(value, str) for value in commands):
        raise CatalogError(f"{context}.commands must be a list of strings")
    return [value.strip() for value in commands]


def _flag_value(tokens: list[str], aliases: tuple[str, ...]) -> str | None:
    for index, token in enumerate(tokens):
        for alias in aliases:
            if token == alias and index + 1 < len(tokens):
                return tokens[index + 1]
            if token.startswith(f"{alias}="):
                return token.split("=", 1)[1]
    return None


def command_topology(command: str) -> dict[str, object]:
    """Extract only topology values explicitly present in one command."""
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()
    topology: dict[str, object] = {}
    for name, aliases in TOPOLOGY_FLAGS.items():
        value = _flag_value(tokens, aliases)
        if value is not None:
            topology[name] = value
    nodes = topology.get("nodes")
    gpus_per_node = topology.get("gpus_per_node")
    if isinstance(nodes, str) and isinstance(gpus_per_node, str) and nodes.isdigit() and gpus_per_node.isdigit():
        topology["total_gpus"] = int(nodes) * int(gpus_per_node)
    return topology


def _entry(
    *,
    model_slug: str,
    workflow: str,
    hardware: str | None,
    variant: str | None,
    source_pointer: str,
    item: dict[str, Any],
    inherited: dict[str, Any],
    dimensions: dict[str, object] | None = None,
) -> dict[str, object]:
    merged = {**inherited, **item}
    status = _text(merged.get("status"))
    if status not in VALID_STATUSES:
        raise CatalogError(f"{source_pointer}.status must be one of {sorted(VALID_STATUSES)}")
    commands = _commands(merged, source_pointer)
    identity = [model_slug, workflow]
    if hardware:
        identity.append(hardware)
    if variant:
        identity.append(variant)
    entry_id = _slug("-".join(identity))
    return {
        "entry_id": entry_id,
        "source_pointer": source_pointer,
        "workflow": workflow,
        "hardware": hardware,
        "variant": variant,
        "status": status,
        "precision": _text(merged.get("precision")),
        "last_verified": _text(merged.get("last_verified")),
        "bridge_commit": _text(merged.get("bridge_commit")),
        "commands": commands,
        "command_topologies": [command_topology(command) for command in commands],
        "dimensions": _json_value(dimensions or {}),
        "enabled_features": _json_value(merged.get("enabled_features", {})),
        "metrics": _json_value(merged.get("metrics", {})),
        "expected_result": _text(merged.get("expected_result")),
    }


def _normal_item_entries(
    model_slug: str,
    workflow: str,
    hardware: str | None,
    source_pointer: str,
    item: dict[str, Any],
    inherited: dict[str, Any],
) -> list[dict[str, object]]:
    if "variants" in item:
        variants = _mapping(item["variants"], f"{source_pointer}.variants")
        parent = {**inherited, **{key: value for key, value in item.items() if key != "variants"}}
        return [
            _entry(
                model_slug=model_slug,
                workflow=workflow,
                hardware=hardware,
                variant=str(name),
                source_pointer=f"{source_pointer}.variants.{name}",
                item=_mapping(value, f"{source_pointer}.variants.{name}"),
                inherited=parent,
            )
            for name, value in variants.items()
        ]
    if "points" in item:
        points = item["points"]
        if not isinstance(points, list):
            raise CatalogError(f"{source_pointer}.points must be a list")
        parent = {**inherited, **{key: value for key, value in item.items() if key != "points"}}
        entries = []
        for index, point_value in enumerate(points):
            point = _mapping(point_value, f"{source_pointer}.points[{index}]")
            num_gpus = point.get("num_gpus")
            variant = f"{num_gpus}-gpu" if num_gpus is not None else f"point-{index + 1}"
            dimensions = {
                str(key): _json_value(value)
                for key, value in point.items()
                if key
                not in {
                    "status",
                    "precision",
                    "last_verified",
                    "bridge_commit",
                    "command",
                    "commands",
                    "metrics",
                    "enabled_features",
                    "expected_result",
                }
            }
            entries.append(
                _entry(
                    model_slug=model_slug,
                    workflow=workflow,
                    hardware=hardware,
                    variant=variant,
                    source_pointer=f"{source_pointer}.points[{index}]",
                    item=point,
                    inherited=parent,
                    dimensions=dimensions,
                )
            )
        return entries
    return [
        _entry(
            model_slug=model_slug,
            workflow=workflow,
            hardware=hardware,
            variant=None,
            source_pointer=source_pointer,
            item=item,
            inherited=inherited,
        )
    ]


def normalize_card(card_path: Path, repo_root: Path) -> dict[str, object]:
    """Normalize one YAML card into exact concrete configurations."""
    with card_path.open(encoding="utf-8") as stream:
        card = _mapping(yaml.safe_load(stream), str(card_path))
    model = _mapping(card.get("model"), f"{card_path}: model")
    environment = _mapping(card.get("verification_environment"), f"{card_path}: verification_environment")
    items = _mapping(card.get("items"), f"{card_path}: items")
    model_slug = card_path.parent.name
    entries: list[dict[str, object]] = []
    inherited = {"bridge_commit": environment.get("bridge_commit")}
    for workflow, raw_item in items.items():
        item = _mapping(raw_item, f"items.{workflow}")
        source_pointer = f"items.{workflow}"
        if "status" in item and any(key in item for key in ("command", "commands", "variants", "points")):
            entries.extend(_normal_item_entries(model_slug, workflow, None, source_pointer, item, inherited))
            continue
        for hardware, raw_hardware_item in item.items():
            hardware_item = _mapping(raw_hardware_item, f"{source_pointer}.{hardware}")
            entries.extend(
                _normal_item_entries(
                    model_slug,
                    workflow,
                    str(hardware),
                    f"{source_pointer}.{hardware}",
                    hardware_item,
                    inherited,
                )
            )
    pointers = [str(entry["source_pointer"]) for entry in entries]
    entry_ids = [str(entry["entry_id"]) for entry in entries]
    if len(pointers) != len(set(pointers)):
        raise CatalogError(f"{card_path} contains duplicate normalized source pointers")
    if len(entry_ids) != len(set(entry_ids)):
        raise CatalogError(f"{card_path} produces duplicate entry ids")
    return {
        "slug": model_slug,
        "title": _text(card.get("title")) or model_slug,
        "summary": _text(card.get("summary")) or "",
        "source_card": card_path.relative_to(repo_root).as_posix(),
        "hf_id": _text(model.get("hf_id")) or "",
        "hf_revision": _text(model.get("hf_revision")),
        "architecture": _text(model.get("architecture")),
        "min_transformers_version": _text(model.get("min_transformers_version")),
        "base_container": _text(environment.get("base_container")),
        "bridge_commit": _text(environment.get("bridge_commit")),
        "entries": entries,
    }


def build_catalog(repo_root: Path) -> dict[str, object]:
    """Discover all cards and build the versioned normalized catalog."""
    cards = sorted(repo_root.glob(CARD_GLOB))
    if not cards:
        raise CatalogError(f"no cards matched {CARD_GLOB}")
    models = [normalize_card(card, repo_root) for card in cards]
    models.sort(key=lambda model: (str(model["hf_id"]).casefold(), str(model["slug"])))
    return {
        "schema_version": CATALOG_SCHEMA_VERSION,
        "source": CARD_GLOB,
        "generation": "offline-derived; YAML cards remain authoritative",
        "models": models,
    }


def _md_cell(value: object | None) -> str:
    if value is None or value == "":
        return "—"
    return str(value).replace("|", "\\|").replace("\n", " ")


def _status_label(status: str) -> str:
    return STATUS_LABELS[status]


def _model_status(entries: list[dict[str, object]]) -> str:
    statuses = {str(entry["status"]) for entry in entries}
    if statuses == {"verified"}:
        return "verified"
    if "verified" in statuses:
        return "partially verified"
    for status in ("unverified", "unsupported", "not_applicable"):
        if status in statuses:
            return status.replace("_", " ")
    raise CatalogError("model has no concrete configuration status")


def _find_model_doc(repo_root: Path, model: dict[str, object]) -> str:
    needles = [str(model["source_card"]), str(model["hf_id"]), str(model["slug"])]
    candidates: list[tuple[int, int, str]] = []
    for path in sorted((repo_root / "docs/models").rglob("*.md")):
        content = path.read_text(encoding="utf-8")
        score = sum((3 - index) for index, needle in enumerate(needles) if needle and needle in content)
        if score:
            relative = path.relative_to(repo_root / "docs").as_posix()
            candidates.append((-score, len(relative), relative))
    if not candidates:
        return "models/README.md"
    return min(candidates)[2]


def _catalog_rows(catalog: dict[str, object], *, fern: bool) -> list[str]:
    rows = [
        "| Model | Workflow | Hardware | Precision | Status | Last verified | Concrete configuration |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for model in catalog["models"]:
        model_data = _mapping(model, "catalog model")
        slug = str(model_data["slug"])
        for raw_entry in model_data["entries"]:
            entry = _mapping(raw_entry, f"{slug} entry")
            page = f"./models/{slug}" if fern else f"models/{slug}.md"
            variant = entry.get("variant") or "default"
            if fern:
                link = f"[{_md_cell(variant)}]({page}#{entry['entry_id']})"
            else:
                link = f'<a href="models/{slug}.html#{entry["entry_id"]}">{_md_cell(variant)}</a>'
            rows.append(
                "| "
                + " | ".join(
                    [
                        f"[{_md_cell(model_data['hf_id'])}]({page})",
                        _md_cell(entry["workflow"]),
                        _md_cell(entry.get("hardware") or "not specified"),
                        _md_cell(entry.get("precision") or "not specified"),
                        _md_cell(_status_label(str(entry["status"]))),
                        _md_cell(entry.get("last_verified")),
                        link,
                    ]
                )
                + " |"
            )
    return rows


def render_catalog_page(catalog: dict[str, object], *, fern: bool) -> str:
    """Render the complete static catalog page for Sphinx or Fern."""
    models = [_mapping(model, "catalog model") for model in catalog["models"]]
    entry_count = sum(len(model["entries"]) for model in models)
    lines = [
        GENERATED_NOTICE,
        "",
        "# Model Verification Catalog",
        "",
        "This catalog is generated offline from the authoritative YAML verification cards. "
        "Every row below maps to exactly one concrete card item, variant, or weak-scaling point; "
        "the catalog never combines independent fields into a synthetic command.",
        "",
        f"Current inventory: **{len(models)} model cards** and **{entry_count} concrete configurations**.",
        "",
        "Statuses are explicit: ✅ **verified**, ⚪ **unverified**, ❌ **unsupported**, and "
        "➖ **not applicable**. A model page may summarize mixed concrete states as partially verified.",
        "",
        "Regenerate or check these derived files offline with "
        "`uv run --no-project --with pyyaml python scripts/docs/generate_model_verification_catalog.py` "
        "or the same command plus `--check`.",
        "",
        "## Normalization contract",
        "",
        f"The generated data uses normalized schema version **{CATALOG_SCHEMA_VERSION}**:",
        "",
        "- A terminal item or hardware leaf becomes one concrete configuration.",
        "- Each declared `variants` member becomes one configuration; variant fields are never crossed.",
        "- Each declared weak-scaling `points` member becomes one configuration with its own dimensions, "
        "  command, and metrics.",
        "- `command` and ordered `commands` values are copied from that exact leaf. Parent provenance and "
        "  expected results may be inherited only along the leaf's existing YAML path.",
        "",
        "This Stage 0/1 delivery intentionally leaves cross-model comparison, selector URL state, and "
        "freshness policy for a follow-up. Those features need explicit schema semantics and a safe build "
        "hook before they can be offered without fabricating combinations. The historical performance "
        "summary remains separate; metrics shown here come only from verification cards.",
        "",
    ]
    if fern:
        lines.extend(
            [
                "Use the documentation search or the complete static table below. The current Fern "
                "configuration has no repository-local JavaScript build hook, so URL-backed selectors "
                "and richer Stage 2 comparison controls are intentionally deferred; all content and "
                "commands remain available without JavaScript.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                '<div id="verification-catalog-filters" class="verification-catalog-filters" hidden>',
                '  <label>Search <input id="verification-catalog-search" type="search" '
                'placeholder="model, workflow, hardware, precision, status"></label>',
                '  <label>Workflow <select data-catalog-column="1"><option value="">All</option></select></label>',
                '  <label>Hardware <select data-catalog-column="2"><option value="">All</option></select></label>',
                '  <label>Precision <select data-catalog-column="3"><option value="">All</option></select></label>',
                '  <label>Status <select data-catalog-column="4"><option value="">All</option></select></label>',
                '  <span id="verification-catalog-count" aria-live="polite"></span>',
                "</div>",
                "",
                "The filters use progressive enhancement over this table. Without JavaScript, the complete "
                "catalog and every per-model view remain readable. The versioned normalized data is also "
                "available as [`catalog-v1.json`](../_static/model-verification/catalog-v1.json).",
                "",
            ]
        )
    lines.extend(_catalog_rows(catalog, fern=fern))
    if not fern:
        lines.extend(["", "```{toctree}", ":hidden:", ""])
        lines.extend(f"models/{model['slug']}.md" for model in models)
        lines.append("```")
    return "\n".join(lines).rstrip() + "\n"


def _render_mapping(mapping: object) -> list[str]:
    if not isinstance(mapping, dict) or not mapping:
        return ["None recorded."]
    lines = ["| Field | Value |", "| --- | --- |"]
    for key, value in mapping.items():
        rendered = json.dumps(value, sort_keys=True) if isinstance(value, (dict, list)) else value
        lines.append(f"| `{_md_cell(key)}` | `{_md_cell(rendered)}` |")
    return lines


def _render_topologies(topologies: object) -> list[str]:
    if not isinstance(topologies, list) or not topologies or not any(topologies):
        return ["No launch topology is explicitly encoded in the command."]
    lines = ["| Command | Explicit topology |", "| --- | --- |"]
    for index, topology in enumerate(topologies, start=1):
        if not isinstance(topology, dict) or not topology:
            value = "not specified"
        else:
            value = ", ".join(f"{key}={item}" for key, item in topology.items())
        lines.append(f"| {index} | `{_md_cell(value)}` |")
    return lines


def render_model_page(model: dict[str, object], repo_root: Path, *, fern: bool) -> str:
    """Render one model page from normalized card data."""
    entries = [_mapping(entry, "model entry") for entry in model["entries"]]
    status_counts = Counter(str(entry["status"]) for entry in entries)
    source_url = f"https://github.com/NVIDIA-NeMo/Megatron-Bridge/blob/main/{model['source_card']}"
    hf_url = f"https://huggingface.co/{model['hf_id']}"
    model_doc = _find_model_doc(repo_root, model)
    doc_link = "../../" + (model_doc.removesuffix(".md") if fern else model_doc)
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {_md_cell(model['hf_id'])}",
        "",
        str(model["summary"]),
        "",
        "## Provenance",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Card | [`{_md_cell(model['source_card'])}`]({source_url}) |",
        f"| Hugging Face model | [`{_md_cell(model['hf_id'])}`]({hf_url}) |",
        f"| Hugging Face revision | `{_md_cell(model.get('hf_revision'))}` |",
        f"| Architecture | `{_md_cell(model.get('architecture'))}` |",
        f"| Minimum Transformers | `{_md_cell(model.get('min_transformers_version'))}` |",
        f"| Base container | `{_md_cell(model.get('base_container'))}` |",
        f"| Card-level Bridge commit | `{_md_cell(model.get('bridge_commit'))}` |",
        f"| Complementary model documentation | [Open model guide]({doc_link}) |",
        f"| Aggregate state | **{_model_status(entries)}** |",
        "",
        "Concrete status counts: "
        + ", ".join(f"{_status_label(status)}: **{status_counts.get(status, 0)}**" for status in STATUS_LABELS)
        + ".",
        "",
        "## Concrete configurations",
        "",
        "Each section below is one existing card leaf. Hardware and precision are shown only when the card "
        "states them; missing values are not inferred from prose or neighboring entries.",
    ]
    for entry in entries:
        label_parts = [str(entry["workflow"])]
        if entry.get("hardware"):
            label_parts.append(str(entry["hardware"]))
        if entry.get("variant"):
            label_parts.append(str(entry["variant"]))
        anchor = f'<a id="{entry["entry_id"]}"></a>'
        lines.extend(
            [
                "",
                anchor,
                f"### {' · '.join(label_parts)}",
                "",
                "| Field | Value |",
                "| --- | --- |",
                f"| Status | **{_status_label(str(entry['status']))}** |",
                f"| Source pointer | `{_md_cell(entry['source_pointer'])}` |",
                f"| Hardware | `{_md_cell(entry.get('hardware') or 'not specified')}` |",
                f"| Precision | `{_md_cell(entry.get('precision') or 'not specified')}` |",
                f"| Last verified | `{_md_cell(entry.get('last_verified'))}` |",
                f"| Effective Bridge commit | `{_md_cell(entry.get('bridge_commit'))}` |",
                "",
                "#### Explicit command topology",
                "",
                *_render_topologies(entry["command_topologies"]),
                "",
                "#### Configuration dimensions",
                "",
                *_render_mapping(entry["dimensions"]),
                "",
                "#### Enabled features",
                "",
                *_render_mapping(entry["enabled_features"]),
                "",
                "#### Available metrics",
                "",
                *_render_mapping(entry["metrics"]),
                "",
                "#### Exact command",
                "",
            ]
        )
        commands = entry["commands"]
        if isinstance(commands, list) and commands:
            for index, command in enumerate(commands, start=1):
                if len(commands) > 1:
                    lines.extend([f"Command {index}:", ""])
                command_lines = [line.rstrip() for line in str(command).splitlines()]
                lines.extend(["```bash", *command_lines, "```", ""])
        else:
            lines.extend(["No runnable command is recorded for this status.", ""])
        expected_result = str(entry.get("expected_result") or "None recorded.")
        rendered_result = "\n".join(line.rstrip() for line in expected_result.splitlines())
        lines.extend(["#### Expected result", "", rendered_result])
    return "\n".join(lines).rstrip() + "\n"


def _render_nav_section(catalog: dict[str, object]) -> str:
    lines = [NAV_START, "- section: Model Verification", "  contents:"]
    lines.extend(
        [
            "  - page: Model Verification Catalog",
            "    path: ./nightly/pages/model-verification/index.mdx",
        ]
    )
    for raw_model in catalog["models"]:
        model = _mapping(raw_model, "catalog model")
        lines.append(f"  - page: {json.dumps(str(model['hf_id']))}")
        lines.append(f"    path: ./nightly/pages/model-verification/models/{model['slug']}.mdx")
    lines.append(NAV_END)
    return "\n".join(lines)


def _update_nav(nav_text: str, catalog: dict[str, object]) -> str:
    if NAV_START not in nav_text or NAV_END not in nav_text:
        raise CatalogError(f"Fern navigation must contain {NAV_START!r} and {NAV_END!r}")
    pattern = re.compile(rf"{re.escape(NAV_START)}.*?{re.escape(NAV_END)}", re.DOTALL)
    return pattern.sub(_render_nav_section(catalog), nav_text)


def expected_outputs(repo_root: Path, catalog: dict[str, object]) -> dict[Path, str]:
    """Return every generated artifact and its deterministic content."""
    outputs = {
        repo_root / "docs/model-verification/index.md": render_catalog_page(catalog, fern=False),
        repo_root / "docs/fern/versions/nightly/pages/model-verification/index.mdx": render_catalog_page(
            catalog, fern=True
        ),
        repo_root / "docs/_static/model-verification/catalog-v1.json": json.dumps(catalog, indent=2, sort_keys=True)
        + "\n",
    }
    for raw_model in catalog["models"]:
        model = _mapping(raw_model, "catalog model")
        slug = str(model["slug"])
        outputs[repo_root / f"docs/model-verification/models/{slug}.md"] = render_model_page(
            model, repo_root, fern=False
        )
        outputs[repo_root / f"docs/fern/versions/nightly/pages/model-verification/models/{slug}.mdx"] = (
            render_model_page(model, repo_root, fern=True)
        )
    nav_path = repo_root / "docs/fern/versions/nightly.yml"
    outputs[nav_path] = _update_nav(nav_path.read_text(encoding="utf-8"), catalog)
    return outputs


def generate(repo_root: Path, *, check: bool) -> bool:
    """Write generated outputs, or return whether checked-in outputs match."""
    catalog = build_catalog(repo_root)
    outputs = expected_outputs(repo_root, catalog)
    mismatches: list[str] = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(path.relative_to(repo_root).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    expected_model_files = {
        path.resolve() for path in outputs if path.parent.name == "models" and path.suffix in {".md", ".mdx"}
    }
    for pattern in (
        "docs/model-verification/models/*.md",
        "docs/fern/versions/nightly/pages/model-verification/models/*.mdx",
    ):
        for path in repo_root.glob(pattern):
            if path.resolve() not in expected_model_files:
                if check:
                    mismatches.append(path.relative_to(repo_root).as_posix())
                elif path.read_text(encoding="utf-8").startswith(GENERATED_NOTICE):
                    path.unlink()
    if mismatches:
        LOGGER.error("generated model verification files are stale: %s", ", ".join(sorted(mismatches)))
        return False
    if not check:
        LOGGER.info(
            "generated %d model pages and %d concrete entries",
            len(catalog["models"]),
            sum(len(_mapping(model, "model")["entries"]) for model in catalog["models"]),
        )
    return True


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Megatron Bridge repository root",
    )
    parser.add_argument("--check", action="store_true", help="fail when checked-in generated files are stale")
    return parser.parse_args()


def main() -> int:
    """Run the catalog generator command-line interface."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = _parse_args()
    try:
        return 0 if generate(args.repo_root.resolve(), check=args.check) else 1
    except (CatalogError, OSError, yaml.YAMLError) as error:
        LOGGER.error("%s", error)
        return 1


if __name__ == "__main__":
    sys.exit(main())
