try:
    import megatron.bridge  # noqa: F401

    HAVE_MEGATRON_BRIDGE = True
except ModuleNotFoundError:
    HAVE_MEGATRON_BRIDGE = False

if HAVE_MEGATRON_BRIDGE:
    from .deepseek_llm_pretrain import (
        deepseek_v3_pretrain_config_b200_config,
        deepseek_v3_pretrain_config_gb200_config,
        deepseek_v3_pretrain_config_gb300_config,
        deepseek_v3_pretrain_config_h100_config,
    )

from .deepseek_workload_base_configs import (
    DEEPSEEK_V3_PRETRAIN_CONFIG_B200_BF16_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_CS_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_MX_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_BF16_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_CS_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_MX_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_BF16_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_CS_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_MX_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_NVFP4_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_H100_BF16_BASE_CONFIG,
    DEEPSEEK_V3_PRETRAIN_CONFIG_H100_FP8_CS_BASE_CONFIG,
)


__all__ = [
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B200_BF16_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_CS_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_MX_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_BF16_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_CS_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_MX_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_BF16_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_CS_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_MX_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_NVFP4_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_H100_BF16_BASE_CONFIG",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_H100_FP8_CS_BASE_CONFIG",
]

if HAVE_MEGATRON_BRIDGE:
    __all__.extend(
        [
            "deepseek_v3_pretrain_config_gb300_config",
            "deepseek_v3_pretrain_config_gb200_config",
            "deepseek_v3_pretrain_config_b200_config",
            "deepseek_v3_pretrain_config_h100_config",
        ]
    )
