# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:25.11-py3
FROM ${BASE_IMAGE}

ARG NCCL_VERSION=2.30.7-1+cuda13.3

RUN --mount=type=bind,source=docker/common/install_nccl.sh,target=/opt/install_nccl.sh \
    --mount=type=bind,source=docker/common/validate_nccl.sh,target=/opt/validate_nccl.sh \
    bash /opt/install_nccl.sh --NCCL_VER="${NCCL_VERSION}" && \
    bash /opt/validate_nccl.sh "${NCCL_VERSION}"
