#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)

export NUM_GPUS=8
export NNODES=4
export TENSOR_PARALLEL_SIZE=2
export PIPELINE_PARALLEL_SIZE=2
export CONTEXT_PARALLEL_SIZE=1
export EXPERT_MODEL_PARALLEL_SIZE=8
export EXPERT_TENSOR_PARALLEL_SIZE=1
export SEQUENCE_PARALLEL=True
export SEQ_LENGTH=16384
export GLOBAL_BATCH_SIZE=16
export MICRO_BATCH_SIZE=1
export FREEZE_LANGUAGE_MODEL=False
export FREEZE_VISION_MODEL=True
export FREEZE_AUDIO_MODEL=True
export VIT_GRADIENT_CHECKPOINTING=False
export MULTIMODAL_ATTN_IMPL=auto
export ATTENTION_BACKEND=flash
export RECOMPUTE_GRANULARITY=full
export RECOMPUTE_METHOD=uniform
export RECOMPUTE_NUM_LAYERS=12
export RECOMPUTE_MODULES=core_attn
export OPTIMIZER_CPU_OFFLOAD=False
export OPTIMIZER_OFFLOAD_FRACTION=0.0
export USE_PRECISION_AWARE_OPTIMIZER=False
export OVERLAP_GRAD_REDUCE=False
export OVERLAP_PARAM_GATHER=False
export ALIGN_PARAM_GATHER=False
export GPU_PEAK_TFLOPS_PER_DEVICE=${GPU_PEAK_TFLOPS_PER_DEVICE:-312}

# Short run for profiling.
export TRAIN_ITERS=${TRAIN_ITERS:-20}
export LOG_INTERVAL=${LOG_INTERVAL:-1}
export RUN_NAME=${RUN_NAME:-qwen3_omni_sft32_tp2_pp2_ep8_sp_profile}
export TENSORBOARD_DIR=${TENSORBOARD_DIR:-/nfs/ofs-llab-hdd/users/liuwei/omni/qwen3_omni_train/results/${RUN_NAME}/tb_logs}

# Profiling controls (PyTorch profiler).
export USE_PYTORCH_PROFILER=${USE_PYTORCH_PROFILER:-True}
export USE_NSYS_PROFILER=${USE_NSYS_PROFILER:-False}
export PROFILE_STEP_START=${PROFILE_STEP_START:-10}
export PROFILE_STEP_END=${PROFILE_STEP_END:-12}
export PROFILE_RANKS=${PROFILE_RANKS:-[0]}
export PYTORCH_PROFILER_COLLECT_SHAPES=${PYTORCH_PROFILER_COLLECT_SHAPES:-False}
export PYTORCH_PROFILER_COLLECT_CALLSTACK=${PYTORCH_PROFILER_COLLECT_CALLSTACK:-False}
export PYTORCH_PROFILER_COLLECT_CHAKRA=${PYTORCH_PROFILER_COLLECT_CHAKRA:-False}
export RECORD_MEMORY_HISTORY=${RECORD_MEMORY_HISTORY:-False}
export NVTX_RANGES=${NVTX_RANGES:-True}

echo "[info] profiling run: TP=${TENSOR_PARALLEL_SIZE} PP=${PIPELINE_PARALLEL_SIZE} EP=${EXPERT_MODEL_PARALLEL_SIZE} SP=${SEQUENCE_PARALLEL} SEQ=${SEQ_LENGTH} GBS=${GLOBAL_BATCH_SIZE} MBS=${MICRO_BATCH_SIZE}"
echo "[info] recompute: ${RECOMPUTE_GRANULARITY}/${RECOMPUTE_METHOD}/${RECOMPUTE_NUM_LAYERS} modules=${RECOMPUTE_MODULES}"
echo "[info] overlap: grad_reduce=${OVERLAP_GRAD_REDUCE} param_gather=${OVERLAP_PARAM_GATHER} align_param_gather=${ALIGN_PARAM_GATHER}"
echo "[info] profiler: pytorch=${USE_PYTORCH_PROFILER} nsys=${USE_NSYS_PROFILER} steps=${PROFILE_STEP_START}-${PROFILE_STEP_END} ranks=${PROFILE_RANKS}"
echo "[info] tensorboard: ${TENSORBOARD_DIR}"

bash "${SCRIPT_DIR}/local_train_thinker_full.sh"
