#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)

MODE=${MODE:-ep8}

case "${MODE}" in
  ep8)
    export NUM_GPUS=${NUM_GPUS:-8}
    export TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-1}
    export PIPELINE_PARALLEL_SIZE=${PIPELINE_PARALLEL_SIZE:-1}
    export CONTEXT_PARALLEL_SIZE=${CONTEXT_PARALLEL_SIZE:-1}
    export EXPERT_MODEL_PARALLEL_SIZE=${EXPERT_MODEL_PARALLEL_SIZE:-8}
    export EXPERT_TENSOR_PARALLEL_SIZE=${EXPERT_TENSOR_PARALLEL_SIZE:-1}
    export SEQUENCE_PARALLEL=${SEQUENCE_PARALLEL:-False}
    export RUN_NAME=${RUN_NAME:-qwen3_omni_full_train_ep8}
    ;;
  tp2_ep4)
    export NUM_GPUS=${NUM_GPUS:-8}
    export TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-2}
    export PIPELINE_PARALLEL_SIZE=${PIPELINE_PARALLEL_SIZE:-1}
    export CONTEXT_PARALLEL_SIZE=${CONTEXT_PARALLEL_SIZE:-1}
    export EXPERT_MODEL_PARALLEL_SIZE=${EXPERT_MODEL_PARALLEL_SIZE:-4}
    export EXPERT_TENSOR_PARALLEL_SIZE=${EXPERT_TENSOR_PARALLEL_SIZE:-1}
    export SEQUENCE_PARALLEL=${SEQUENCE_PARALLEL:-False}
    export RUN_NAME=${RUN_NAME:-qwen3_omni_full_train_tp2_ep4}
    ;;
  *)
    echo "Unknown MODE=${MODE}. Supported: ep8, tp2_ep4" >&2
    exit 1
    ;;
esac

echo "[info] MODE=${MODE}"
echo "[info] NUM_GPUS=${NUM_GPUS}"
echo "[info] TP=${TENSOR_PARALLEL_SIZE} PP=${PIPELINE_PARALLEL_SIZE} CP=${CONTEXT_PARALLEL_SIZE} EP=${EXPERT_MODEL_PARALLEL_SIZE} ETP=${EXPERT_TENSOR_PARALLEL_SIZE} SP=${SEQUENCE_PARALLEL}"

bash "${SCRIPT_DIR}/local_train_thinker_full.sh"
