name: Azure Queue Events Template

on:
  workflow_call:
    inputs:
      worker_configs:
        description: |
          JSON string containing list of worker configurations for the matrix.
          Example: '[{"id": 1, "runner": "ubuntu-latest", "cpu-only": true}, {"id": 2, "runner": "windows-latest", "cpu-only": false}]'
        required: true
        type: string
      events:
        description: |
          JSON string containing list of events to add to the queue.
          Example: '[{"type": "event1", "name": "test1", "script": "echo test1"}]'
        required: true
        type: string
    secrets:
      AZURE_BLOB_STORAGE:
        required: true
      AZURE_QUEUE_STORAGE_ACCOUNT:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  AZURE_QUEUE_STORAGE_ACCOUNT: ${{ secrets.AZURE_QUEUE_STORAGE_ACCOUNT }}
  AZURE_BLOB_STORAGE: ${{ secrets.AZURE_BLOB_STORAGE }}
  AZURE_STORAGE_QUEUE_NAME: events-queue-${{ github.run_id }}

jobs:
  start-queue-workers:
    uses: ./.github/workflows/start-queue-workers.yml
    with:
      worker_configs: ${{ inputs.worker_configs }}
      worker-timeout: "10"
      test-timeout: "10"
    secrets:
      AZURE_BLOB_STORAGE: ${{ secrets.AZURE_BLOB_STORAGE }}
      AZURE_QUEUE_STORAGE_ACCOUNT: ${{ secrets.AZURE_QUEUE_STORAGE_ACCOUNT }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  monitor-logs:
    name: monitor-logs-${{ matrix.event.type }}
    needs: start-queue-workers
    runs-on: ubuntu-latest
    environment: nemo-ci
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        event: ${{ fromJson(inputs.events) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Monitor Queue Logs
        uses: ./.github/actions/monitor-queue-logs
        with:
          event-type: ${{ matrix.event.type }}
          event-name: ${{ matrix.event.name }}
          event-script: ${{ matrix.event.script }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-queue-name: ${{ env.AZURE_STORAGE_QUEUE_NAME }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-queue-storage-account: ${{ secrets.AZURE_QUEUE_STORAGE_ACCOUNT }}
          azure-blob-storage: ${{ secrets.AZURE_BLOB_STORAGE }}
          is-unit-test: false
          timeout: 10

  stop-workers:
    needs: [monitor-logs]
    if: always()  # Run even if other jobs were cancelled
    runs-on: ubuntu-latest
    environment: nemo-ci
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Emit Stop Events
        uses: ./.github/actions/emit-stop-events
        with:
          queue-name: ${{ env.AZURE_STORAGE_QUEUE_NAME }}
          num-workers: 3
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-queue-storage-account: ${{ secrets.AZURE_QUEUE_STORAGE_ACCOUNT }}
