name: Example Queue Processing

on:
  push:

jobs:
  process-queue:
    uses: ./.github/workflows/azure-queue-events.yml
    with:
      # Example 1: Simple worker configs (just numbers)
      worker_configs: |
        [
          1,
          2,
          3
        ]

      # Example 2: Complex worker configs with custom settings
      # worker_configs: |
      #   [
      #     {
      #       "id": 1,
      #       "batch_size": 10,
      #       "timeout": 30
      #     },
      #     {
      #       "id": 2,
      #       "batch_size": 20,
      #       "timeout": 60
      #     },
      #     {
      #       "id": 3,
      #       "batch_size": 15,
      #       "timeout": 45
      #     }
      #   ]

      # Example events to process
      events: |
        [
          {
            "type": "event_1",
            "name": "First Event",
            "script": "echo 'Processing First Event'"
          },
          {
            "type": "event_2",
            "name": "Second Event",
            "script": "echo 'Processing Second Event'"
          },
          {
            "type": "event_3",
            "name": "Third Event",
            "script": "echo 'Processing Third Event'"
          },
          {
            "type": "event_4",
            "name": "Fourth Event",
            "script": "echo 'Processing Fourth Event'"
          },
          {
            "type": "event_5",
            "name": "Fifth Event",
            "script": "echo 'Processing Fifth Event'"
          },
          {
            "type": "event_6",
            "name": "Sixth Event",
            "script": "echo 'Processing Sixth Event'"
          },
          {
            "type": "event_7",
            "name": "Seventh Event",
            "script": "echo 'Processing Seventh Event'"
          },
          {
            "type": "event_8",
            "name": "Eighth Event",
            "script": "echo 'Processing Eighth Event'"
          },
          {
            "type": "event_9",
            "name": "Ninth Event",
            "script": "echo 'Processing Ninth Event'"
          },
          {
            "type": "event_10",
            "name": "Tenth Event",
            "script": "echo 'Processing Tenth Event'"
          }
        ]
    secrets:
      AZURE_BLOB_STORAGE: ${{ secrets.AZURE_BLOB_STORAGE }}
      AZURE_QUEUE_STORAGE_ACCOUNT: ${{ secrets.AZURE_QUEUE_STORAGE_ACCOUNT }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
