name: Installation Test

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

jobs:
  install-test:
    runs-on: ${{ matrix.arch }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install project
        run: |
          pip install ".[eval,recipes]"

  uv-test:
    runs-on: ${{ matrix.arch }}
    name: UV on ${{ matrix.arch }}
    environment: nemo-ci
    strategy:
      fail-fast: false
      matrix:
        arch: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v1
        with:
          version: 0.7.2

      - name: Set up yq
        shell: bash
        run: |
          if [[ "${{ matrix.arch }}" == "ubuntu-latest" ]]; then
            BINARY="yq_linux_amd64"
          else
            BINARY="yq_linux_arm64"
          fi

          wget https://github.com/mikefarah/yq/releases/download/v4.45.4/$BINARY.tar.gz
          tar -xzf $BINARY.tar.gz
          mkdir -p ./bin
          mv $BINARY ./bin/yq 
          chmod +x ./bin/yq

      - name: Install dependencies with UV
        env:
          UV_PROJECT_ENVIRONMENT: ./venv
          PAT: ${{ secrets.PAT }}
        run: |
          echo -e "machine github.com\n  login token\n  password $PAT" > ~/.netrc
          chmod 600 ~/.netrc 

          export PATH=".bin/:$PATH"

          uv venv ${UV_PROJECT_ENVIRONMENT}

          uv sync --link-mode copy --locked --all-groups

          bash ./docker/common/install_conflicting_deps.sh \
            --export-deploy-ref $(cat ./docker/manifest.json | yq -r '.vcs-dependencies.export-deploy.ref')
